# Enedis service.
fetch_datas:
  name: Fetch datas
  fields:
    entry:
      name: Entry
      required: true
      selector:
        config_entry:
          integration: myelectricaldata
    service:
      name: Service
      required: true
      default: daily_production
      selector:
        select:
          mode: dropdown
          options:
            - label: Daily Consumption
              value: daily_consumption
            - label: Detail Consumption
              value: consumption_load_curve              
            - label: Daily Production
              value: daily_production
            - label: Detail Production
              value: production_load_curve
    start_date:
      name: Start Date
      description: Start date
      required: true
      selector:
        datetime:
    end_date:
      name: End Date
      description: End date
      required: true
      selector:
        datetime:
    price:
      name: Price
      description: Price
      required: false
      selector:
        number:
          min: 0
          max: 100     
          step: 0.001    
          mode: box  
    off_price:
      name: Offpeak Price
      description: Offpeak Price
      required: false
      selector:
        number:
          min: 0
          max: 100     
          step: 0.001
          mode: box          

# Enedis service.
clear_datas:
  name: Clear datas
  fields:
    statistic_id:
      name: Statistic Id
      description: set statistic_id , you pick in statistic from developer page
      required: true
      selector:
        text:
