# Enedis service.
fetch_data:
  name: Fetch datas
  description: Fetch and add data in statistics database
  fields:
    entry:
      name: Entry
      description: PDL entity
      required: true
      selector:
        config_entry:
          integration: myelectricaldata
    service:
      name: Service
      description: Type of data to retrieve 
      required: true
      default: daily_production
      selector:
        select:
          mode: dropdown
          options:
            - label: Daily Consumption
              value: daily_consumption
            - label: Detail Consumption
              value: consumption_load_curve              
            - label: Daily Production
              value: daily_production
            - label: Detail Production
              value: production_load_curve
    start_date:
      name: Start Date
      description: Recovery start date
      required: true
      selector:
        datetime:
    end_date:
      name: End Date
      description: Recovery end date
      required: true
      selector:
        datetime:
    price:
      name: Price
      description: Price
      required: false
      selector:
        number:
          min: 0
          max: 100     
          step: 0.001    
          mode: box  
    off_price:
      name: Offpeak Price
      description: Offpeak Price (Only if detailed mode)
      required: false
      selector:
        number:
          min: 0
          max: 100     
          step: 0.001
          mode: box          

# Enedis service.
clear_data:
  name: Clear datas
  description: clear data statistics in your database
  fields:
    statistic_id:
      name: Statistic Id
      description: set statistic_id , you pick in statistic from developer page
      required: true
      selector:
        text:
